---
title: "Function Demonstrations"
output:
  html_document:
    theme: cerulean
---

```{r}
#library(devtools)
#install_github("jamesbeeson01/Saunders")
library(tidyverse)
library(Saunders)
```

# geom_predict()

This function uses predict() to create any line from any linear model, even high dimensional models with y transformations.

The first argument


Y Transformations

```{r}
lm.log <- lm(log(hwy) ~ displ, data = mpg)

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_predict(lm.log, trans = exp)
```

Prediction Interval

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_predict(lm.log, trans = exp, interval = "prediction", color = "green")
```

Complex X Functions

```{r}
lm.displ2 <- lm(hwy ~ displ + I(displ^2), mpg)

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_predict(lm.displ2)
```

Additional Variables

```{r}
lm.drv <- lm(hwy ~ displ + I(displ^2) + displ:drv, mpg)

ggplot(mpg, aes(displ, hwy, color = drv)) +
  geom_point() +
  geom_predict(lm.drv, data.frame(drv = "4"), color = "red") +
  geom_predict(lm.drv, data.frame(drv = "f"), color = "green") +
  geom_predict(lm.drv, data.frame(drv = "r"), color = "blue") +
  scale_color_manual(values = c("red", "green", "blue"))
```